### ISSUE TITLE
i dont know how to comment but i need chapter 1 season 3 ( patch 3.20)

### ISSUE THREAD

**Issue by senttohxll** [xdjxsonnn/Fortnite-Heightmaps#1]
not sure how to export heightmaps, but if you could export that one or tell me how you did these, that would be great.

**Comment by xdjxsonnn** [comment]
Which heightmap do you need I'll make it for you (Fortnite) Patch 13.00?

**Comment by senttohxll** [comment]
Chapter 1 season 3, second patch, so patch 3.20. The original season 3.
