### ISSUE TITLE
I'm slightly confused with the Height Maps

### ISSUE THREAD

**Issue by SnakeyFlea** [xdjxsonnn/Fortnite-Heightmaps#2]
I'm slightly confused with the Height Maps as when i import them into UEFN they are way to big.
![github](https://github.com/xdjxsonnn/Fortnite-Heightmaps/assets/96121681/a3d94eb9-aac1-4225-a68b-bdb07cb59301)

**Comment by xdjxsonnn** [comment]
![Settings](https://github.com/xdjxsonnn/Fortnite-Heightmaps/assets/135362740/0e2602ed-ccdc-4817-b1a6-fa28cc373432)

**Comment by SnakeyFlea** [comment]
Thanks! 😁
