### ISSUE TITLE
I'm confused on the material 

### ISSUE THREAD

**Issue by cfbv2121** [xdjxsonnn/Fortnite-Heightmaps#3]
How do I get all of the choices that are here?https://media.discordapp.net/attachments/822568989309534268/1149754906580877352/image.png?width=460&height=488
when I try to use /Script/Engine.Material'/Game/Athena/Environments/Landscape/Creative/M_Athena_Terrain_DefaultBiome_02.M_Athena_Terrain_DefaultBiome_02' these are the only options I get 
![image](https://github.com/xdjxsonnn/Fortnite-Heightmaps/assets/145526069/c2cac02d-4f3e-4446-a0f1-c32a9423c807)

**Comment by xdjxsonnn** [comment]
You habe to create your own material.

**Comment by cfbv2121** [comment]
How do I get Normals and R G Bs for old textures?

**Comment by xdjxsonnn** [comment]
![Screenshot_20230921_073444_YouTube](https://github.com/xdjxsonnn/Fortnite-Heightmaps/assets/135362740/b441ff72-82c8-49da-b8c1-32308039a6bc)

**Comment by xdjxsonnn** [comment]
For example

**Comment by cfbv2121** [comment]
I see, but I am meaning for the Athena terrain. I cannot find the purple or blue variants I can only find the base colors 
![Athena_GrassBiome_M_02](https://github.com/xdjxsonnn/Fortnite-Heightmaps/assets/145526069/92de3e88-e7ab-4767-a5b0-b3bef3406633)

**Comment by cfbv2121** [comment]
This is the only one I could find, However it looks bad when I put it with the grass texture

**Comment by cfbv2121** [comment]
Can you give me the textures you used? If possible
