### ISSUE TITLE
How to use the layers info folder in UEFN ?

### ISSUE THREAD

**Issue by zebrazit** [xdjxsonnn/Fortnite-Heightmaps#6]
Hey!
With the height map folder we also have a _layer_ folder containing several layers info of the different biomes, roads... what is it for? How can I use it in **UEFN**? 
Thank you in advance.

**Comment by xdjxsonnn** [comment]
Hello, you can import the layer using the landscape tool that you normally use to export the height maps or layer as the following image shows it.
![image](https://github.com/xdjxsonnn/Fortnite-Heightmaps/assets/135362740/7cade94d-a17e-4ef5-a091-d64115889c28)

**Comment by zebrazit** [comment]
Ok, thank you, so I have to start by adding the height map, then I add all the layers of the folder. But what should I do to add the textures of each layer?

**Comment by zebrazit** [comment]
Yes I'm new...I've already made some maps that didn't require too much knowledge. My discord is 0hug

**Comment by xdjxsonnn** [comment]
Ok, well, I'm very happy to help you on discord because I've been doing Unreal Engine and Fortnite and Uefn as a whole for about 9 months They are always happy to solve any questions for you. BTW I sent you a friend request!

**Comment by GoldenNiteDev** [comment]
I actually do have a question. How do you have access to the Athena Master Material for the terrain? If you could, please help me gain access to this. If discord works better for you when communicating, you can send me a request to GoldenNiteGaming.

**Comment by xdjxsonnn** [comment]
Hello, I have a tool that allows you the conversion from .json to Unreal Engine for Fortnite : https://github.com/GMatrixGames/JsonAsAsset

**Comment by xdjxsonnn** [comment]
Take a look at the chat and everything should be well described there

**Comment by GoldenNiteDev** [comment]
I learned how to use the landscape layers. If you want, you can DM me on Discord and I'll explain it for you.

**Comment by MatVecchi22** [comment]
Don't worry i figured out how to use them. Just one thing, do you know if with JsonAsAsset you can extract all the terrain materials such as the road, the mud, etc? The ones I'm searching for are the chapter 1 materials

**Comment by xdjxsonnn** [comment]
Yes, all that are in the current game!

**Comment by MatVecchi22** [comment]
but i found only the default terrain. Do you know where are the other ones? Because online i found only the season 5 materials, but i didn't find what i am searching for, that are all the season 3 materials

**Comment by MatVecchi22** [comment]
My idea is to get a copy of the default terrain material and then modify it to add the road, mud, and forest grass layers so i can use the layers info to recreate the chapter 1 season 3 map. do you know if there is a better way to do it?

**Comment by xdjxsonnn** [comment]
What do you mean "I found them online"?

**Comment by MatVecchi22** [comment]
online i found that you can access the season 5 material by pasting a specific path (for example the default terrain is /Script/Engine.Material'/Game/Athena/Environments/Landscape/Creative/M_Athena_Terrain_DefaultBiome_02.M_Athena_Terrain_DefaultBiome_02') directly in UEFN, also i tried to go into that location with FModel but i didn't find anything else than those materials.
