### ISSUE TITLE
how to paint the sand snow and darker grass

### ISSUE THREAD

**Issue by TiltedFN10** [xdjxsonnn/Fortnite-Heightmaps#7]
how do i make the snow desert and the darker areas + volcano on the season x height map?
![Screenshot 2024-01-27 042344](https://github.com/xdjxsonnn/Fortnite-Heightmaps/assets/114893756/3eceddf7-bf41-467f-8ccf-9c9a6426f689)

**Comment by xdjxsonnn** [comment]
Hello, you have to create yourself in material like I did to be able to use all layers
![ScreenShot00014](https://github.com/xdjxsonnn/Fortnite-Heightmaps/assets/135362740/043fd808-7573-4bc7-85b4-ebecec9fe780)
![ScreenShot00015](https://github.com/xdjxsonnn/Fortnite-Heightmaps/assets/135362740/b052b2ec-8663-4a1e-8c32-0ade369f5d1d)
![ScreenShot00016](https://github.com/xdjxsonnn/Fortnite-Heightmaps/assets/135362740/3c8a6df8-088d-4f02-8a9e-70ae586ed7f9)

**Comment by TiltedFN10** [comment]
ok but how do i do that

**Comment by xdjxsonnn** [comment]
Tutorials on youtube?

**Comment by TiltedFN10** [comment]
yes but where do i find the textures

**Comment by xdjxsonnn** [comment]
Fmodel

**Comment by TiltedFN10** [comment]
i finally got season x downloaded  but how do i import master texture into uefn?

**Comment by xdjxsonnn** [comment]
You have to make your own material with the textures etc...

**Comment by TiltedFN10** [comment]
ok ill try to do it ..
